baseURL = "https://of-mu.org/"
languageCode = "en-us"
title = "Of Mu"
theme="hugo-theme-nix"

[params]
  GithubID = "overlordofmu"
  TwitterID = "overlordofmu"
  LinkedInID = "lawsonluke"
  GoogleplusID = "+LukeLawson-mu"
  Name = "Luke Lawson"
  HeaderUsername = "overlord"
  HeaderHostname = "of-mu.org"
  Email = "overlord@of-mu.org"
  About = "Luke is an autodidactic polymath with a passion for information systems. He finds new challenges invigorating and loves evolving to meet dynamic requirements."
  ProfilePicture = "luke.png"
  SlackURL = "https://of-mu.slack.com/team/U7A9RHKK7"
  #  GoogleAnalytics = "your_google_analytics_id"
[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
