[build]
  publish = "public"
  command = "hugo && env &&  identify -version ; free -h  && echo hello there"
  onInit = "echo \"onInit starting\""

[dev]
  command = "hugo serve" # Command to start your dev server
#  port = 8888   # The port that the netlify dev will be accessible on
  publish = "public" # The path to your static content folder

[context.deploy-preview]
  command = ""

[context.'slash/in/name/branch']
  command = "hugo  || echo 'slash-in-name-branch build' "

## Comment for new commit
