[build]
  publish = "public"
  command = "hugo && env &&  sleep 10 && echo hello"
  onInit = "echo \"onInit starting\""

[dev]
  command = "hugo serve" # Command to start your dev server
#  port = 8888   # The port that the netlify dev will be accessible on
  publish = "public" # The path to your static content folder

[context.deploy-preview]
  command = "ls -alH ; free -h ; env ; sleep 20 ; hugo  || { sleep 30 ; false ; } "

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    checkExternal = false
    entryPoints = [
      "*.html"
    ]
    followSourceMaps = false
    pretty = true
    recursive = true
    skipPatterns = []
    todoPatterns = []