[build]
  command = "env ; hugo || { sleep 120; false; } ; sleep 600 "
  HUGO_VERSION = "0.20"

[context.deploy-preview]
  command = "hugo"

#comments still trigger builds :)
#comments still trigger builds :)
#comments still trigger builds :)
#comments still trigger builds :)
#comments still trigger builds :)