[build]
command = "free -h ; env ; hugo  || { sleep 120; false; }"

[build.environment]
  HUGO_VERSION = "0.53"

[context.deploy-preview]
  command = "free -h ; env ; hugo  || { sleep 120 ; false ; } "
