[build]
  publish = "public"
  command = "hugo && env &&  sleep 10 && echo hello"
  onInit = "echo \"onInit starting\""

[context.deploy-preview]
  command = "ls -alH ; free -h ; env ; hugo  || { sleep 120 ; false ; } "

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    checkExternal = false
    entryPoints = [
      "*.html"
    ]
    followSourceMaps = false
    pretty = true
    recursive = true
    skipPatterns = []
    todoPatterns = []