[build]
command = "env ; hugo"

[build.environment]
#  HUGO_VERSION = "0.56.3"

[context.deploy-preview]
  command = "ls -alH ; free -h ; env ; hugo  || { sleep 120 ; false ; } "


#comments still trigger builds :)
