[build]
publish = "public"

[build.lifecycle]
onBuild = "hugo && env &&  sleep 60 && echo hello"
onInit = "echo \"onInit starting\""

[context]

[context.deploy-preview]
command = "ls -alH ; free -h ; env ; hugo  || { sleep 120 ; false ; } "

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.config]
checkExternal = false
entryPoints = ["*.html"]
followSourceMaps = false
pretty = true
recursive = true
skipPatterns = []
todoPatterns = []

