[build]
  publish = "public"
  command = "hugo && env &&  identify -version ; free -h  && echo hello there"
  onInit = "echo \"onInit starting\""
  functions = "functions"

[dev]
  command = "hugo serve" # Command to start your dev server
#  port = 8888   # The port that the netlify dev will be accessible on
  publish = "public" # The path to your static content folder

[context.deploy-preview]
  command = "ls -alH ; identify -version ;  free -h ; env ; sleep 20 ; hugo  || { sleep 30 ; false ; } "


[[headers]]
  for = "/*"
  [headers.values]
    X-Pretend = "Let's pretend this is www.of-mu.org"


[[headers]]
  for = "/*"
  [headers.values]
    X-Pretend = "Let's pretend this is mufu.io"

[[redirects]]
  from = "/proxy/*"
  to = "https://2ad358630a285c3e77fe1405e0d92e9f.m.pipedream.net/:splat"
  status = 200
  headers = {Origin = "www.sunweb.nl"}
