[context.production.environment]
  HUGO_VERSION = "0.23"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.208"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.staging] # 'staging' is a branch name
  command = "echo 'staging'"
  base = "staging"

## A comment to trigger a deploy
